Iter5
lookeme/short-url pull request #5
Opened 2024-04-14 20:36 UTC by lookeme

Iteration 5

2024-04-16 23:15 UTC, avhitrov requested changes
Хороший код. Есть несколько придирок, отмечены в комментариях. Дел по исправлению на полбанана.

2024-04-16 23:15 UTC, avhitrov commented on internal/server/handler/handlers.go
> +	}
Имеет смысл проверить входные данные на соответствие формату url. Хотя бы с помощью url.Parse.

2024-04-16 23:15 UTC, avhitrov commented on internal/server/handler/handlers.go
> +	}
Реакцию на эту ошибку нет смысла бросать пользователю, так как это тот же канал, в котором она возникла. И в нем уже выставлен статус. Правильнее залогировать и больше ничего не делать.

2024-04-16 23:15 UTC, avhitrov commented on internal/server/handler/handlers.go
> +	id := req.RequestURI[1:]
```suggestion
	id := chi.URLParam(req, "id")
```
иначе зачем описывать `{id}` в раутере?

2024-04-17 06:55 UTC, lookeme commented on internal/server/handler/handlers.go
> +	id := req.RequestURI[1:]
Ага, а я пробовал достать вот так id := req.PathValue("id"), но не отработал(

2024-04-17 09:36 UTC, lookeme commented on internal/server/handler/handlers.go
> +	}
done

2024-04-22 16:51 UTC, Perederey approved these changes
Все супер, только лишь супер мелкие замечания

2024-04-22 16:51 UTC, Perederey commented on cmd/shortener/flag.go
> +	"github.com/lookeme/short-url/internal/configuration"
Надо сделать сортировку с помощью go imports

2024-04-22 16:51 UTC, Perederey commented on cmd/shortener/flag.go
> +	networkCfg = configuration.NetworkCfg{}
А зачем переменными? Можно лучше сделать через dependency injection паттерн

2024-04-22 16:51 UTC, Perederey commented on internal/app/domain/shorten/shorten.go
> +		token := utils.NewShortToken(7)
Что если второй раз будет повтор?

2024-04-22 16:51 UTC, Perederey commented on internal/server/handler/handlers_test.go
> +		url := strings.Split(string(responseBody), "/")
Лучше всю строку целиком

2024-04-22 16:51 UTC, Perederey commented on internal/server/http/http_server.go
> +	ConfigFile = os.Getenv("CONFIG_FILE")
Так не надо, лучше через dependency injection и потом запускать в main

2024-04-22 16:51 UTC, Perederey commented on internal/server/http/http_server.go
> +	fmt.Printf("Starting server on port %s", s.Config.ServerAddress)
Здесь лучше бы логгер

2024-04-22 16:51 UTC, Perederey commented on internal/storage/inmemory/shorten.go
> +	keyToURL map[string]string
Можно сразу map из пакета sync использовать

2024-04-22 17:33 UTC, lookeme commented on internal/server/http/http_server.go
> +	fmt.Printf("Starting server on port %s", s.Config.ServerAddress)
логгер в следующем спринте

2024-04-22 17:37 UTC, lookeme commented on cmd/shortener/flag.go
> +	"github.com/lookeme/short-url/internal/configuration"
а чем она лучше, чем gofmt?

2024-04-22 17:37 UTC, lookeme commented on cmd/shortener/flag.go
> +	"github.com/lookeme/short-url/internal/configuration"
![Uploading Снимок экрана 2024-04-22 в 20.37.10.png…]()

2024-04-22 17:45 UTC, lookeme commented on internal/app/domain/shorten/shorten.go
> +		token := utils.NewShortToken(7)
Если второй раз прилетит существующий ключ, то он вернет уже существующее значение. Ничего перезаписывать не будет.

2024-04-22 17:46 UTC, lookeme commented on internal/storage/inmemory/shorten.go
> +	keyToURL map[string]string
можно.

2024-04-22 17:47 UTC, merged